### ISSUE TITLE
Roller Brackets "Resting Tabs" Out of location

### ISSUE THREAD

**Issue by leitenky** [VoronDesign/VoronUsers#1001]
Mod in question https://github.com/VoronDesign/VoronUsers/tree/master/printer_mods/ommy/roller_brackets
When I tried to mount the roller Brackets, the brackets lift the printer about  5mm, resulting the the rubber feet not touching the "table top"

Moving the horizontal resting surface down about 6mm would fix the issue. Would it be possible to get the files updated, or post the original Cad files and I will modify as required?

**Comment by FHeilmann** [comment]
@omelethc can you help out here?
