### ISSUE TITLE
Support RGB NeoPixels mounting

### ISSUE THREAD

**Issue by shkup** [VoronDesign/VoronUsers#1009]
As the title suggest, I think a solution for RGB NeoPixels mounting instead of sequins leds would benefit the community.

**Comment by FHeilmann** [comment]
Hi, thanks for your suggestion, unfortunately this isn't really the place for such requests. I suggest you join the VoronDesign discord (https://discord.gg/voron) and talk to some people in the `#voronuser_mods` channel about your idea.

Bests,

Florian
