### ISSUE TITLE
[MOD ISSUE] Screws does´nt fit 

### ISSUE THREAD

**Issue by fabiandj64** [VoronDesign/VoronUsers#1043]
### Which mod does this issue apply to?

PsychoShaft/C92X_PsycHoShafts_Mount

### Relevant VoronDesign printer

Voron Trident

### Describe the bug

In the assembly instruction it is mentioned to use the screws you disassembled earlier. But they wont fit with the adapter plate; you need longer screws to attach the plate but i dont know which screws i need

**Comment by newphreak** [comment]
@PsychoShaft: anything you could help with?

**Comment by PsychoShaft** [comment]
To properly attach the camera, you'll need to utilize the four screws located on its bottom. Insert these screws through the mount and secure them back into the camera. This ensures a stable and secure connection between the camera and its mount.

**Comment by fabiandj64** [comment]
I tried to secure the cameramount with the 4 bottom screws but they are to short to screw through the mount and grab on to the thread in the camera

Maybe there are different versions of this camera because my screws are black. On the pictures in your mod, they look like normal silverish screws

**Comment by PsychoShaft** [comment]
can you send me a photo on discord? i have the same name on discord. ( psychoshaft )

**Comment by fabiandj64** [comment]
it works with the provided screws i dont know why it did not work in the first place, but i got it with a little force
