### ISSUE TITLE
[MOD ISSUE] Wago Extrusion Mounts Collision with Deck Panel

### ISSUE THREAD

**Issue by stfngnsch** [VoronDesign/VoronUsers#1049]
### Which mod does this issue apply to?

printer_mods/LoganFraser/WagoMounts

### Relevant VoronDesign printer

On my V2.4

### Describe the bug

The Wago Extrusion Mounts collide with the Deck Panel under the Bed. If you compare the parts with the original mount "wago_221-415_mount_3x5.stl" in "Electronics_Bay", you can see that the mounting hole is lower. 

![Screenshot 2024-06-27 071837](https://github.com/VoronDesign/VoronUsers/assets/100370956/ff6343aa-489f-4b06-9afd-2afda7032353)

### Addition information

Had a really hard time mounting the brackets until I realised they just don't fit.

**Comment by newphreak** [comment]
@LoganFraser: Do you have any input here? :)
