### ISSUE TITLE
Afterburner files available on request

### ISSUE THREAD

**Issue by mateuszbrzezinski** [VoronDesign/VoronUsers#128]
"Afterburner files available on request" How can I get Afterburner files for 2.4?

**Comment by spott** [comment]
what files are you looking for?

The f3d files for 2.4 contain all of afterburner.

**Comment by mateuszbrzezinski** [comment]
Sorry, I though it will be linked to what I meant.
I meant this: https://github.com/VoronDesign/VoronUsers/tree/8f43acee8ba7549add9e005fe9325dc8d10554b6/legacy_printers/printer_mods/Slidr/PanzerChain

there is written: (Afterburner files available on request)

**Comment by spott** [comment]
Ah.

I would hop on discord and ping that user (Slidr), he would be the one to ask.

**Comment by FHeilmann** [comment]
@Slidr666 your presence is requested :)

**Comment by Slidr666** [comment]
Actully readme seems to be outdated there.  There are already Afterburner Beta files available.

**Comment by FHeilmann** [comment]
@mateuszbrzezinski I think this issue is "resolved" now right? I hope you've gotten the parts you've needed from Slidr on discord. If not, feel free to reopen this issue.
