### ISSUE TITLE
Different wiring required for SKR Mini E3 V2.0

### ISSUE THREAD

**Issue by Lefuneste83** [VoronDesign/VoronUsers#228]
First of all thank you for this great little mod.
I have encountered a little difficulties wiring it to the latest SKR Mini E3 V2.0. On this card, Klipper does not support I2C protocol on the LCD connector. 
Then you need to :
-Wire the screen to the Raspberry Pi directly : SDA (PIN 3), SCL (PIN 5), 5V (PIN 2 or 4) and GND (PIN 6 or 9 or other GND available). See GPIO pinouts on google. 
-Enable I2C interface on the RPi with raspi-config in SSH.
-Install a specific script and compile / flash a klipper firmware for a Linux process according to this procedure : 
https://www.klipper3d.org/RPi_microcontroller.html
-Then declare new entries in printer.cfg. Here's mine : 

> [mcu host]
> serial: /tmp/klipper_host_mcu
> 
> [display]
> lcd_type: ssd1306
> i2c_mcu: host
> i2c_bus: i2c.1
> 
> [display_status]

Then it works perfectly.

There is a thread for this Klipper "regression" on this specific board version here : 
https://github.com/KevinOConnor/klipper/issues/3581

**Comment by FHeilmann** [comment]
Feel free to submit an example config for this board to be stored here alongside the other configurations. At this point I'm not sure if this is a PSA or if you're raising this issue against something already included in this repo.

I'll close this issue for now, but feel free to get back to me about it.

-Florian
