### ISSUE TITLE
color_order_GRB config option has been removed

### ISSUE THREAD

**Issue by mhk-v0** [VoronDesign/VoronUsers#311]
The neopixel color_order_GRB config option has been removed. If necessary, update the config to set the new color_order option to RGB, GRB, RGBW, or GRBW.

So it has to be `color_order: GRB` in the printer.cfg

Just wanne let people know who try to copy paste the config. Thanks

**Comment by FHeilmann** [comment]
Thanks for this issue, I believe all official Voron configurations have been updated to reflect that. if you catch that error in any of the configurations we put out, please let us know.
