### ISSUE TITLE
Lumentec deliver wrong profiles

### ISSUE THREAD

**Issue by DoXer67** [VoronDesign/VoronUsers#312]
The linked seller of the profiles "Lumentec" delivers wrong profiles. The described profiles are 18,35mm and not 17mm.

This just for information.

**Comment by Cataclysm** [comment]
Have the same issue. Printed parts will not fit the 18.35mm profiles.

**Comment by DoXer67** [comment]
Get in contact with with Lumentec. I returned the 18,35mm and get the correct ones.

**Comment by xp1ratex** [comment]
Got those from Lumentec, had to scale the printed piece to 104%, now its working.

**Comment by FHeilmann** [comment]
Hi, it seems to me this was a supplier issue, that has since been resolved? Anyway since this issue has not seen any traffic for some time, I'm going to close it for now.
