### ISSUE TITLE
Galileo Extruder supported in your BadNoob AB design?

### ISSUE THREAD

**Issue by netweaver1970** [VoronDesign/VoronUsers#336]
Hi,
I would like to use the latest Galileo extruder design together with the BadNoob improved AB design, using a Dragon HF hot-end.

I'm not sure both designs are compatible right now, Can you comment on that?

Thanks.

**Comment by AaronHerrick** [comment]
Yes, I used Galileo while developing ab-bn, and Jared has been a big help.

**Comment by netweaver1970** [comment]
Thanks. This was just for confirmation. Closing the issue.
