### ISSUE TITLE
Consider linking with CadHub

### ISSUE THREAD

**Issue by Irev-Dev** [VoronDesign/VoronUsers#340]
Just a quick suggestion since you've got both openscad files and STL files in this repo and I'm sure it's a pain updating the STLs each time there's a change to the SCAD code.

CadHub has a feature that allows you to link to an external url to fetch code.

To take @evandepol 's the DIN-Rail-Cable-Mount as an example, the following url: https://github.com/VoronDesign/VoronUsers/blob/master/printer_mods/evandepol/Voron2.4-Cable-clamps/CAD/DIN-Rail-Cable-Mount-350mm.scad

Is encoded into this CadHub url:
https://cadhub.xyz/dev-ide/openScad#fetch_text_v1=https%3A%2F%2Fgithub.com%2FVoronDesign%2FVoronUsers%2Fblob%2Fmaster%2Fprinter_mods%2Fevandepol%2FVoron2.4-Cable-clamps%2FCAD%2FDIN-Rail-Cable-Mount-350mm.scad

![image](https://user-images.githubusercontent.com/29681384/121150344-cae35100-c886-11eb-81ed-9d6746ae026a.png)

So that it can be fetched on the fly, meaning that the link will automatically stay up-to-date with the repo, so the link could be added to a readme or even just in a comment at the top of the code.

I'm the main dev behind CadHub, so I'm trying to improve it as I go, but one big limitation to this approach atm is that it's single file only, i.e. the [Combination Clamp](https://github.com/VoronDesign/VoronUsers/blob/2b083e727004e1e355ca93ffe3eb5768045b53f0/printer_mods/evandepol/Voron2.4-Cable-clamps/CAD/Combination-Clamp-and-Ramp-350mm.scad) won't work because it uses `use <>` statements. Multi-file projects is on the TODO list though.

Also unfortunately I haven't added proper UI for making these urls but the structure is just `https://cadhub.xyz/dev-ide/openScad#fetch_text_v1=<you-url>`, the included url doesn't have to be encoded but it makes it safer, an easy way to get the url is to go to the file you're interested in on github, open the dev tools and paste the following into the console:
`'https://cadhub.xyz/dev-ide/openScad#fetch_text_v1=' + encodeURIComponent(location.href)`
And that should give you the url.

Anyway ignore me if this isn't useful. Feel free to let me know if you have any feedback about Cadhub too.

**Comment by raymondh2** [comment]
The files included are not managed by the Voron Design team. We also require STLs be included in the repo itself not hosted externally.
