### ISSUE TITLE
Backpanel pcb for fan control

### ISSUE THREAD

**Issue by dragsterbox** [VoronDesign/VoronUsers#411]
Hello,

Where can I get this pcb ?

![image](https://user-images.githubusercontent.com/37857756/130365539-4b7fed5a-92e8-43e3-bd4d-0384013b8987.png)

**Comment by VinnyCordeiro** [comment]
> 
> 
> Hello,
> 
> Where can I get this pcb ?
> 
> ![image](https://user-images.githubusercontent.com/37857756/130365539-4b7fed5a-92e8-43e3-bd4d-0384013b8987.png)

On the Voron Hardware repo: https://github.com/VoronDesign/Voron-Hardware/tree/master/V0_PCB_Mod

**Comment by FHeilmann** [comment]
Since this issue seems to have been resolved/answered I'll close it for now.
