### ISSUE TITLE
Unable to clone repo due to filename length (GadgetAngel)

### ISSUE THREAD

**Issue by bigjoe4265** [VoronDesign/VoronUsers#483]
Unable to clone repo.  Filename is too long.

printer_mods/GadgetAngel/Cricut_Voron_Logos/Voron_SW_Logo/1_Color_Layer_WithOut_Logo_Outline_WithOut_Silhouette/Cricut_VoronSW_Logo_RearPanel_1Layer_WithOut_Logo_Outline_WithOUT_Silhouette_and_BackPanel.jpg: Filename too long
error: unable to create file 

error: unable to create file printer_mods/GadgetAngel/Cricut_Voron_Logos/Voron_SW_Logo/1_Color_Layer_WithOut_Logo_Outline_WithOut_Silhouette/Cricut_VoronSW_Logo_RearPanel_IndividualObjects_1Layer_WithOut_Logo_Outline_WithOUT_Silhouette.ai: Filename too long

**Comment by FHeilmann** [comment]
Unfortunately the powershell and GUI versions of github don't like long filenames. Please use the github command line (from cmd or a bash shell) to clone the repo, or download it using githubs "Download as zip" option.
