### ISSUE TITLE
wile-e1 Deck_Panel_Support_Clips adjustable support step file missing

### ISSUE THREAD

**Issue by crashmaxx** [VoronDesign/VoronUsers#491]
[https://github.com/VoronDesign/VoronUsers/tree/master/printer_mods/wile-e1/Deck_Panel_Support_Clips](url)
@wile-e1 

wile.e-deck_panel_support_lower_adjustable(3-6mm).stp is the same file as wile.e-deck_panel_support_lower_4mm.stp so the step file of the adjustable version is not in the repo.

The stl files are correct, the adjustable and 4mm versions are different.

**Comment by FHeilmann** [comment]
This was fixed with PR https://github.com/VoronDesign/VoronUsers/pull/584 Thank you for your report.
