### ISSUE TITLE
M3 Heat insert in AB-BN BOM needs detail updating

### ISSUE THREAD

**Issue by simonrwatts** [VoronDesign/VoronUsers#524]
@AaronHerrick BOM currently shows "M3x0.5 Heat set insert". This made me and others start searching. I had to search Discord for an answer.

Ideally it would read 'M3x5x4mm Heat Set insert (Same as Voron BOM)' to make it 100% clear :)

**Comment by AaronHerrick** [comment]
OK, I'll make the update

**Comment by FHeilmann** [comment]
Closing due to stale-ness and AB-BN being part of the official Voron ecosystem within SB
