### ISSUE TITLE
Help：The temperature of the extruder header  can not rised  190+ °C

### ISSUE THREAD

**Issue by knight350147** [VoronDesign/VoronUsers#538]
Hi guys:
    When I test my machine(Voron 2.4 Extruder PID test),The fludd always reports errors like the picture.And the temperature freezd 190°C  ：

![1](https://user-images.githubusercontent.com/95066460/143733112-9f3dba51-29ee-4f50-9e52-58e55bb91148.png)

The printer.cfg
![image](https://user-images.githubusercontent.com/95066460/143733205-5fafef01-9369-4ce5-8ad8-dde52d3bc75a.png)

Board：fysetc spider
klipper+fuidd

Who can help me?

**Comment by knight350147** [comment]
remark：sensor type like this：
![image](https://user-images.githubusercontent.com/95066460/143733855-4fd7537a-03fd-4306-9166-42747e218a87.png)

**Comment by FHeilmann** [comment]
This is not the place to ask for priner supprot, please join our discord or use our reddit instead.
