### ISSUE TITLE
350mm skirt's are both skirt b on 5 inch Display mount

### ISSUE THREAD

**Issue by jaredb03** [VoronDesign/VoronUsers#612]
The skirts for the 350mm build are the same skirt. Both are the B skirt.

**Comment by FHeilmann** [comment]
Which mod are you referring to?

**Comment by jaredb03** [comment]
Sorry the 5 inch mount. https://github.com/VoronDesign/VoronUsers/tree/master/printer_mods/Tircown/Display_mount_5inch
