### ISSUE TITLE
Badnoob/AB-BN/AB-BN-30_Assy.f3d  dragon back size bug!

### ISSUE THREAD

**Issue by corogoo** [VoronDesign/VoronUsers#621]
https://github.com/VoronDesign/VoronUsers/blob/master/printer_mods/Badnoob/AB-BN/AB-BN-30_Assy.f3d
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/10955343/153784149-0ef454b2-1927-4fd2-8056-d357276e397e.png">

**Comment by raymondh2** [comment]
@Badnoob-327

**Comment by FHeilmann** [comment]
AB-BN has since been incorporated into Stealthburner so I'm going to close this for now due to lack of activity. Please reopen if any new developments arise.
