### ISSUE TITLE
VEFACH modification needed for r2 exhaust housing

### ISSUE THREAD

**Issue by pgale** [VoronDesign/VoronUsers#653]
Not sure if kevinakasam#2097 is around or will see this but the VEFACH parts don't fit the 2.4r2 exhaust housing due to the new screw fixings for the exhaust cover getting in the way. A mod to the coal container would be great if possible.

Thanks.

**Comment by newphreak** [comment]
Should be fixed now, if not tag `@ kevinakasam` in a new issue report.
