### ISSUE TITLE
Better scrubbing

### ISSUE THREAD

**Issue by rlaferla** [VoronDesign/VoronUsers#673]
Scrubbing currently doesn't always remove excess filament from the nozzle.  The scrubbing routing only scrubs horizontally left to right.  It can be improved by a back and forth scrubbing.  Here's working code BUT it hasn't been tested on other purge bucket locations.  Just the default rear/left on a Trident.

ALSO:  I changed the G1 codes to G0 codes because G1 is intended for moves involving the extruder (printing) whereas G0 is for other movement.  It's recommended to find other places in the macro that use G1 and change them to G0 EXCEPT for ones that involve extrusion like the purge.

```
      ## Perform horizontal wipe. Wipe direction based off bucket_pos for cool random scrubby routine.
      {% for wipes in range(1, (wipe_qty + 1)) %}
         G0 X{brush_start + (brush_width * (1 - bucket_pos))} F{wipe_spd_xy}
         G0 X{brush_start + (brush_width * bucket_pos)} F{wipe_spd_xy}
      {% endfor %}

      ## Perform back/forth wipe.
      G0 X{(brush_start + (brush_width /2) * bucket_pos)} F{wipe_spd_xy}

      {% for wipes in range(1, (wipe_qty + 1)) %}
         G0 Y{Ry}
         G0 Y{Ry-10}
      {% endfor %}
```

**Comment by cbc02009** [comment]
can you provide a link to the mod you're referring to? kind of hard to help otherwise.

**Comment by rlaferla** [comment]
This is for the nozzle scrubber / purge bucket mod.
