### ISSUE TITLE
V0.1 Movable Pulley Z Drive Mod erro

### ISSUE THREAD

**Issue by skyaee** [VoronDesign/VoronUsers#738]
V0.1 Movable Pulley Z Drive Mod!

[image](https://user-images.githubusercontent.com/40803751/170920873-073494db-4e8b-4596-8118-cd191d05a182.png)

The position of the Top Idler will touch the orange protective cover of the nozzle, causing the X-axis to fail to return

**Comment by nhchiu** [comment]
Sorry, I didn't noticed that since I have not used a dragon hotend.
I'll try to make an update with more clearance.
Thanks a lot for the feedback.

**Comment by newphreak** [comment]
fix merged
