### ISSUE TITLE
2.4 compatible mod but not for 2.4r2

### ISSUE THREAD

**Issue by Blinker73** [VoronDesign/VoronUsers#823]
After printing the exhaust_housing_side_fitting mod by togi, I noticed it dit not fit the exhaust cover I had.
Turns out the mod's design is based on the original 2.4 exhaust with only one center screw for the cover where the new 2.4r2 revision has 2 screws for the cover.

It would be nice to mention this information in the readme.

**Comment by newphreak** [comment]
@togi
