### ISSUE TITLE
STL File name typo in printer_mods/RockNLol

### ISSUE THREAD

**Issue by Blinker73** [VoronDesign/VoronUsers#826]
Some files in this forder are suffixed with _r1 or _r2 based on the voron 2.4 revision

This file is just suffixed with _r without a revision number but is actually a 2.4r2 replacement file
https://github.com/VoronDesign/VoronUsers/blob/master/printer_mods/RockNLol/RockNRoll/STLs/%5Ba%5D_z_drive_baseplate_b_rnl_mod_r.stl

**Comment by newphreak** [comment]
@RockNLol
