### ISSUE TITLE
samwiseg0/LRS PSU Screw Terminal Cover (24v) needs a trim

### ISSUE THREAD

**Issue by wrwindsor** [VoronDesign/VoronUsers#829]
The 24v cover is too thick on the end tabs.

One side was pushing the trim pot over and the other side wouldn't fit between the bus bar and the PS frame. This is a BOM-spec power supply from Digi-Key -- MW LRS-200-24.

I shaved 1mm off of both ends and re-established the chamfers. It's still tight enough to not fall out if tilted.

Attached is the STEP file for my modified version.

[lrs-200_screw_terminal_cover-wrw.zip](https://github.com/VoronDesign/VoronUsers/files/9627436/lrs-200_screw_terminal_cover-wrw.zip)

**Comment by LongDono** [comment]
Yes, ran into the same issue. The right side alone is so wide that it would need the space between the PS frame and the width of the bus bar if I were to fit.

**Comment by newphreak** [comment]
@samwiseg0
