### ISSUE TITLE
Tool Free Tensioner MOD - STL/CAD differes, STL dimensions are out of spec

### ISSUE THREAD

**Issue by hadesfactor617** [VoronDesign/VoronUsers#858]
After printing the tool free tensioner, the pulleys would barely fit into the tensioner.  After taking measurements of the original voron Z-idler tensioner, I noticed the dimensions where 1mm off.  I was going to just edit the CAD until I noticed the CAD is completely different geometry then the STL posted.

Also, the README calls for 4x the hardware for 4 idlers, and to print 4 wheels but says to print only 2 tensioners and 2 brackets.  Seems as though there should be 4xbracket and tensioners but also an A/B side

top= stl, bttm=CAD

Blue tensioner=MOD, Black=Orig Voron2.4r2

![image](https://user-images.githubusercontent.com/38828351/200862517-6c039d2c-98e8-4737-bb20-faf49557035e.png)
![image](https://user-images.githubusercontent.com/38828351/200862704-5cb9a4ad-1500-40f7-be0c-76a705e0ef35.png)

Not sure if this was designed for the R1 in mind 

![20221109_074637](https://user-images.githubusercontent.com/38828351/200861994-6abd3b9a-7c04-45ba-9a32-223925fc5a3f.jpg)
![20221109_074626](https://user-images.githubusercontent.com/38828351/200862029-66a72fcf-5f7f-4a9f-816b-7b2d26bd9df5.jpg)

**Comment by RainerBetrug** [comment]
[Z Achse Gurtstraffer.zip](https://github.com/VoronDesign/VoronUsers/files/10099165/Z.Achse.Gurtstraffer.zip)

**Comment by newphreak** [comment]
@Chaoticlab: is this something you could answer?
