### ISSUE TITLE
[Suggestion] Switchwire Y Tensioner

### ISSUE THREAD

**Issue by droans** [VoronDesign/VoronUsers#859]
For the Y tensioner by mckurt, I believe that using M3 with a heat set insert instead of the M5 screw for the tensioner screw would perform better. 

The design likely would not need to change much. The cap and body would need their center hole shrunk by a couple millimeters and the bearing block will need it's hole shrunk - a small amount for the first 4mm and about 2mm for the rest. 

Plastic works fine for screws if there is no need for a heavy amount of force and if the screw is not adjusted often. However, if either of those are true it will quickly strip. 

An M3 screw with an insert should have a better hold than an M5 screwed directly into plastic, especially as the screw is loosened/tightened over time. 

Paging @MCKURT11.

**Comment by newphreak** [comment]
Try paging him directly on discord. Closing this for now as there's no response.
