### ISSUE TITLE
Hidden cable routing z belt cover mod not fitting when following r2 build instructions

### ISSUE THREAD

**Issue by scheini79** [VoronDesign/VoronUsers#910]
When attaching the Z rails following the build manual for r2 it suggests a gap of approx. 3mm (Page 25). Hidden cable routing z belt cover mod is 5mm in height, thus not fitting under the rails. I did a remix to get rid of the problem.

I'm not sure if this is the right place for a remix, i'm fairly new to GitHub, so please bear with me.
![manual z rails](https://user-images.githubusercontent.com/64658111/219017430-a84c6cba-c857-455e-ad37-96e3ec504ed9.PNG)
![z belt cover](https://user-images.githubusercontent.com/64658111/219017445-4c7a758e-2e73-4f27-be4f-0d9efb48303b.PNG)
[cable_routing_z_belt_cover_a_mod v1.zip](https://github.com/VoronDesign/VoronUsers/files/10742445/cable_routing_z_belt_cover_a_mod.v1.zip)
 Attached you will find the .f3d with my solution.

**Comment by jd766** [comment]
The files haven't been updated with the correction above, this issue still exists

**Comment by newphreak** [comment]
does #872 have this fix, or should it combine it?

**Comment by FHeilmann** [comment]
since this is an issue with a Base Voron part, please submit an issue to the appropriate printer repo if the issue still persists.
