### ISSUE TITLE
[AB-BN-30]  Volcano v6 support

### ISSUE THREAD

**Issue by pasha4ur** [VoronDesign/VoronUsers#912]
Hello

Can you add support of volcano v6, please?

There is also a short heatsink for v6.

![IMG_20230219_041301_284](https://user-images.githubusercontent.com/8062377/219908505-67e73f45-eae1-443c-a769-ff2f8dc87fda.jpg)
![IMG_20230219_041256_914](https://user-images.githubusercontent.com/8062377/219908507-7e31f176-3cdc-4e69-b72b-e0106edf49c3.jpg)

**Comment by Badnoob-327** [comment]
Sorry, but I don't really have plans to add anything to abbn.  Stealthburner is the successor to ABBN, and it surpasses it in many ways.
