### ISSUE TITLE
How is the rapido wire supposed to fit in ABBN 30 rapido STL?

### ISSUE THREAD

**Issue by DanaFo** [VoronDesign/VoronUsers#928]
I can't figure out an orientation to mount the rapido so the bulge of the wire/tab doesn't interfere with the actual mount?

**Comment by timmit99** [comment]
@DanaFo are you referring to a specific mod here? There are hundreds and without more information we can't help you =)

**Comment by DanaFo** [comment]
> @DanaFo are you referring to a specific mod here? There are hundreds and without more information we can't help you =)

lol my apologies, I thought it was a contextual link

**Comment by FHeilmann** [comment]
ABBN was superseded by Stealthburner, which hopefully has all the required documentation. Feel free to reopen if this is not the case.
