### ISSUE TITLE
Z belt cover

### ISSUE THREAD

**Issue by Sidkrsk** [VoronDesign/VoronUsers#936]
It would be good to make a groove under the Z linear guides. Since according to the instructions for voron 2.4 r2, the gap from the bottom is 3 mm, and the plug is 5 mm high and does not get up normally

https://github.com/VoronDesign/VoronUsers/tree/master/printer_mods/Akio/cable_routing_z_belt_cover

**Comment by smplman** [comment]
I needed this also and took a stab at modifying the files. I have them printed and installed on my printer and they are working well. 

https://github.com/smplman/VoronUsers/tree/master/printer_mods/smplman/cable_routing_z_belt_cover_rail_gap/stl

**Comment by FHeilmann** [comment]
@Akio-42  Is this something you could see yourself fixing in the near future?

**Comment by Akio-42** [comment]
@FHeilmann Sure. Did not know about this issue as it was not linked with my current pull request. Will make the change and include it soon.

**Comment by FHeilmann** [comment]
> @FHeilmann Sure. Did not know about this issue as it was not linked with my current pull request. Will make the change and include it soon.

Thanks! Please tag me in the PR once it's ready

**Comment by Akio-42** [comment]
@FHeilmann tagged you at https://github.com/VoronDesign/VoronUsers/pull/872
