### ISSUE TITLE
BTT 7" touch screen enclosure and rail mount

### ISSUE THREAD

**Issue by keshka** [VoronDesign/VoronUsers#945]
I have designed a system for BTT's 7" touch screen allowing it to be attached to a horizontal 2020 rail.
<img width="644" alt="screen box" src="https://user-images.githubusercontent.com/12778097/235052092-e3be36e4-bf27-4114-b985-dafdf0109d6e.png">

I am new at this pull request thing so bear with me

**Comment by FHeilmann** [comment]
Mod submitted as part of https://github.com/VoronDesign/VoronUsers/pull/948
