### ISSUE TITLE
v0.2 Stealth skirts missing parts

### ISSUE THREAD

**Issue by sharpshot21** [VoronDesign/VoronUsers#947]
The V0.2 Stealth Skirts by Maverick mod is missing a couple parts

The parts and the pictures included in the mod show that there are some colored trim pieces that are on the bottom or the corner/feet pieces, those are missing from the file. Thanks for any assistance.

I've linked the mod below
https://github.com/VoronDesign/VoronUsers/tree/master/printer_mods/Maverick/V0.2_Stealth_Skirts#v02-stealth-skirts

Edit: realized that the lcd mount was the stock v0.2 mount

**Comment by nhchiu** [comment]
If you are referring to the accent piece under the feet, yes the STL is missing (At least I can't find it).

I've made several fixes to that mod. Here's the link if you're interested.
https://www.printables.com/model/453847-v02v01-stealth-skirts-mods-and-fixes
