### ISSUE TITLE
2.4 config

### ISSUE THREAD

**Issue by Daz333** [VoronDesign/VoronUsers#950]
Hello everyone
Just finished the build, now all i have to do is install the config file from Lslabs. This one https://github.com/LS-Labs/2.4-config
but its all broke down into [include] files. do i need to make a new file for each one ?

Cheers

**Comment by bdbell** [comment]
This is not the best way of getting that sort of support and that is not our standard configuration. I would either ask about configuration questions in the Discord channel or ask LSLabs how they intended it to be setup.

**Comment by Daz333** [comment]
OK Cheers, sorry about that.
