### ISSUE TITLE
FAN3 Pin Definition

### ISSUE THREAD

**Issue by deadpickle** [VoronDesign/VoronUsers#954]
For the SKR v2 what would the pin description be for FAN3 in the printer.cfg?

**Comment by deadpickle** [comment]
Its between E0M and E1M. It seems like the right place since this is where we get the printer.cfg for the SKR2, but maybe I'm wrong about that

**Comment by timmit99** [comment]
Fan3 is always on, it is not controllable. It is a constant output of whatever the input voltage is.

**Comment by FHeilmann** [comment]
As mentioned, this isn't really the proper place for this question since we are not affiliated with BTT and FAN3 is an always-on fan and therefore not in the PIN lists.
