### ISSUE TITLE
New Version of PiTFT50 

### ISSUE THREAD

**Issue by Sentinel-sys** [VoronDesign/VoronUsers#956]
Hi together,
I just wanted to print the holder for the PiTFT50 since I had to find out that there is now apparently the version v2.1.
This has no more wheel for the screen brightness and also no slide switch for the orientation of the screen.
Both is now regulated with push buttons, a total of three pieces.
Therefore, the 3D model no longer fits the newer displays.
Unfortunately I don't have the possibilities to design something new here, but I'm willing to help with pictures and measurements.
Thank you very much...

Joe

**Comment by FHeilmann** [comment]
@alanho @neggert
