### ISSUE TITLE
Omron Probe always triggered on SKR v2

### ISSUE THREAD

**Issue by deadpickle** [VoronDesign/VoronUsers#957]
I have a TL-Q5MC2-Z probe connected to an SKR v2 (running 2 boards) on a Voron 2.4 build. The 24v is attached to FAN3 and the Signal is plugged into z endstop. The probe is always triggered regardless of the gantry position and I cant seem to figure what is causing it. Any ideas?

printer.cfg:
    [probe]
    ##	Inductive Probe
    ##	This probe is not used for Z height, only Quad Gantry Leveling
    ##	Z_MAX on mcu_z
    ##	If your probe is NO instead of NC, change pin to !^z:PE4
    pin: ^z:PC1
    x_offset: 0
    y_offset: 25.0
    z_offset: 0
    speed: 10.0
    samples: 3
    samples_result: median
    sample_retract_dist: 3.0
    samples_tolerance: 0.006
    samples_tolerance_retries: 3

**Comment by bdbell** [comment]
This is not a good place for support of this type. I would strongly recommend going to the Voron Discord or Forum to ask about it. Thanks.
