### ISSUE TITLE
350mm issue with V2.4 Skirt switch mod by tayto-chip

### ISSUE THREAD

**Issue by TheSin-** [VoronDesign/VoronUsers#959]
Sorry @tayto-gp there is no user with the name tayto-chip on discord which the readme says to contact with issues.

The 350mm side a skirt won't work the nub is too long.

![IMG_8183](https://github.com/VoronDesign/VoronUsers/assets/1868661/ab194d63-67b9-4b9c-99e2-b0c94e56e1ea)
![IMG_8184](https://github.com/VoronDesign/VoronUsers/assets/1868661/46effc7f-29eb-40a2-a077-355e74581478)
![IMG_8185](https://github.com/VoronDesign/VoronUsers/assets/1868661/e004f1a7-148c-48a1-9997-2c842f3a10ac)

**Comment by tayto-gp** [comment]
Hello @TheSin-, I made several fixes to all of these a while back but uploading them has been put on the back burner. Sorry about the issues but thank you for reminding me to update github. In the meantime, if you contact me on discord (tayto #8140) I can send you the updated stl.

**Comment by TheSin-** [comment]
Perfect thank you, message sent.

**Comment by TheSin-** [comment]
this was fixed in the GitHub and I tested it, it's perfect now!
