### ISSUE TITLE
V0.2_Handles unsupported screw holes

### ISSUE THREAD

**Issue by nhchiu** [VoronDesign/VoronUsers#973]
On `V0.2_Handle_Part_A_x2.stl`, The screw hole perimeters are printed mid-air.

![螢幕擷取畫面 2023-07-14 141555](https://github.com/VoronDesign/VoronUsers/assets/14959712/59e91c88-19ee-48fe-8bb7-9b951ff27af7)
![螢幕擷取畫面 2023-07-14 141512](https://github.com/VoronDesign/VoronUsers/assets/14959712/4fa85f9c-a755-429a-93de-d9294ff62c77)

**Comment by FHeilmann** [comment]
Thank you for your report. @Maverick-3D do you see yourself being able to fix this? If so, please respond here. In the meantime I am moving this mod to the orphaned folder
