### ISSUE TITLE
Voron_Parts_Logo.dxf Fails To Load

### ISSUE THREAD

**Issue by eboston** [VoronDesign/VoronUsers#976]
Trying to import the Voron_Parts_Logo.dxf into Fusion 360 and the import fails.  The file may be corrupt.

**Comment by nemgrea** [comment]
imports correctly into solidworks/lightburn/inkscape

![image](https://github.com/VoronDesign/VoronUsers/assets/52015997/16d968b1-5bc9-48c3-bf07-7fe5009baea3)
![image](https://github.com/VoronDesign/VoronUsers/assets/52015997/140f7522-d3a9-40c7-9e98-f0659fae3c06)
![image](https://github.com/VoronDesign/VoronUsers/assets/52015997/0a724479-fc26-4576-94d7-be1b9a26900f)

this is probably an import settings issue on your end.
